// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// ✅ Web config (fixed with your Firebase snippet)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyC9MN4qj6icTTRdg8AGoKnNA-VjqkdHbcM",
    authDomain: "fitnessflex-859b3.firebaseapp.com",
    projectId: "fitnessflex-859b3",
    storageBucket: "fitnessflex-859b3.appspot.com", // fixed
    messagingSenderId: "482222980629",
    appId: "1:482222980629:web:132b7f68cafbb5eb61181c",
    measurementId: "G-TVXYF7FQBZ",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDBsVKKKi5hna437zij5aman4Fm3mVyJdI",
    appId: "1:482222980629:android:f9ed34953a4f297b61181c",
    messagingSenderId: "482222980629",
    projectId: "fitnessflex-859b3",
    storageBucket: "fitnessflex-859b3.appspot.com", // fixed
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyD_tdUYYGldnCS7aWFrZ8fm8Oc8yxsv7Tk",
    appId: "1:482222980629:ios:f090ee325efa2f6f61181c",
    messagingSenderId: "482222980629",
    projectId: "fitnessflex-859b3",
    storageBucket: "fitnessflex-859b3.appspot.com", // fixed
    iosBundleId: "com.devid.fitnessFlexApp",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyD_tdUYYGldnCS7aWFrZ8fm8Oc8yxsv7Tk",
    appId: "1:482222980629:ios:b091d4b1cab1265461181c",
    messagingSenderId: "482222980629",
    projectId: "fitnessflex-859b3",
    storageBucket: "fitnessflex-859b3.appspot.com", // fixed
    iosBundleId: "com.example.fitnessFlexApp",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyC9MN4qj6icTTRdg8AGoKnNA-VjqkdHbcM",
    appId: "1:482222980629:web:438226c80a4f386361181c",
    messagingSenderId: "482222980629",
    projectId: "fitnessflex-859b3",
    authDomain: "fitnessflex-859b3.firebaseapp.com",
    storageBucket: "fitnessflex-859b3.appspot.com", // fixed
    measurementId: "G-EDW1GZEN7R",
  );
}
