import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'package:fitness_flex_app/core/themes/app_theme.dart';
import 'package:fitness_flex_app/navigation/app_router.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await _initFirebase();
  await _initAnonymousSignIn();

  runApp(const FitnessFlexApp());
}

/// Initialize Firebase safely (prevents duplicate-app errors)
Future<void> _initFirebase() async {
  try {
    if (Firebase.apps.isEmpty) {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      debugPrint('✅ Firebase initialized successfully.');
    } else {
      debugPrint('⚠️ Firebase already initialized. Skipping.');
    }
  } catch (e) {
    debugPrint('🔥 Firebase init error: $e');
  }
}

/// Optional: Sign in anonymously for testing if user not logged in
Future<void> _initAnonymousSignIn() async {
  try {
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) {
      await FirebaseAuth.instance.signInAnonymously();
      debugPrint('👤 Signed in anonymously.');
    } else {
      debugPrint('👤 Already signed in as ${user.uid}');
    }
  } catch (e) {
    debugPrint('Auth error: $e');
  }
}

class FitnessFlexApp extends StatelessWidget {
  const FitnessFlexApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FitnessFlex',
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.system,
      initialRoute: AppRouter.splash,
      routes: AppRouter.getRoutes(),
      onGenerateRoute: AppRouter.generateRoute,
      debugShowCheckedModeBanner: false,
    );
  }
}
