import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'package:fitness_flex_app/core/themes/app_theme.dart';
import 'package:fitness_flex_app/navigation/app_router.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Optional: quick way to make logging work without building a full auth UI.
  // Make sure "Anonymous" sign-in is enabled in the Firebase Console.
  try {
    if (FirebaseAuth.instance.currentUser == null) {
      await FirebaseAuth.instance.signInAnonymously();
    }
  } catch (_) {}

  runApp(const FitnessFlexApp());
}

class FitnessFlexApp extends StatelessWidget {
  const FitnessFlexApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FitnessFlex',
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.system,

      // AppRouter controls navigation
      initialRoute: AppRouter.splash,
      routes: AppRouter.getRoutes(),
      onGenerateRoute: AppRouter.generateRoute,

      debugShowCheckedModeBanner: false,
    );
  }
}
